spring:
  application:
    name: namastack-outbox-basic-example

  # Database Configuration (H2 in-memory for demo purposes)
  datasource:
    url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop

# Outbox Configuration
outbox:
  batch-size: 10
  poll-interval: 2000
  schema-initialization:
    enabled: true
  retry:
    policy: jittered
    max-retries: 3
    jittered:
      base-policy: exponential
      jitter: 1000
    exponential:
      initial-delay: 1000
      max-delay: 60000
      multiplier: 2.0
  processing:
    stop-on-first-failure: true
    publish-after-save: true
