# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directories:
      - "/namastack-outbox-examples/namastack-outbox-example-annotation"
      - "/namastack-outbox-examples/namastack-outbox-example-fallback"
      - "/namastack-outbox-examples/namastack-outbox-example-flyway-jdbc"
      - "/namastack-outbox-examples/namastack-outbox-example-flyway-jpa"
      - "/namastack-outbox-examples/namastack-outbox-example-h2"
      - "/namastack-outbox-examples/namastack-outbox-example-java"
      - "/namastack-outbox-examples/namastack-outbox-example-jdbc"
      - "/namastack-outbox-examples/namastack-outbox-example-kafka"
      - "/namastack-outbox-examples/namastack-outbox-example-kafka-java"
      - "/namastack-outbox-examples/namastack-outbox-example-mariadb"
      - "/namastack-outbox-examples/namastack-outbox-example-mongodb"
      - "/namastack-outbox-examples/namastack-outbox-example-multicaster"
      - "/namastack-outbox-examples/namastack-outbox-example-mysql"
      - "/namastack-outbox-examples/namastack-outbox-example-postgresql"
      - "/namastack-outbox-examples/namastack-outbox-example-rabbit"
      - "/namastack-outbox-examples/namastack-outbox-example-rabbit-java"
      - "/namastack-outbox-examples/namastack-outbox-example-retry"
      - "/namastack-outbox-examples/namastack-outbox-example-sns"
      - "/namastack-outbox-examples/namastack-outbox-example-sns-java"
      - "/namastack-outbox-examples/namastack-outbox-example-sqlserver"
      - "/namastack-outbox-examples/namastack-outbox-example-table-prefix-jdbc"
      - "/namastack-outbox-examples/namastack-outbox-example-table-prefix-jpa"
      - "/namastack-outbox-examples/namastack-outbox-example-tracing"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "io.namastack:*"
