changelog:
  exclude:
    labels:
      - release
    authors:
      - github-actions[bot]
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: New Features
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Dependency Updates
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - '*'
      exclude:
        labels:
          - breaking-change
          - enhancement
          - bug
          - documentation
          - dependencies
