services:
  localstack:
    image: localstack/localstack:4.4.0
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: sns
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    volumes:
      - "./init-sns.sh:/etc/localstack/init/ready.d/init-sns.sh"

