services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: outbox_performance_test
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
