spring:
  application:
    name: namastack-outbox-example-modulith

  datasource:
    url: jdbc:h2:mem:modulith-demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop

  modulith:
    events:
      externalization:
        mode: outbox

management:
  observations:
    annotations:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        step: 10s
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs

namastack:
  outbox:
    retry:
      policy: fixed
      fixed:
        delay: 5000
      exclude-exceptions:
        - java.lang.RuntimeException

logging:
  level:
    root: warn
    io.namastack: trace
    org.springframework.modulith.events.kafka: debug
