import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  referenceSidebar: [{type: 'autogenerated', dirName: 'reference'}],
};

export default sidebars;
