package io.namastack.outbox.handler

import org.springframework.aop.support.AopUtils
import org.springframework.core.MethodIntrospector
import org.springframework.core.ResolvableType
import org.springframework.core.annotation.AnnotatedElementUtils
import org.springframework.util.ReflectionUtils
import java.lang.reflect.Method

/**
 * Utility object for common reflection operations on handler methods.
 *
 * Provides reusable functions for:
 * - Resolving target classes behind AOP proxies
 * - Resolving generic interface payload types
 * - Finding interface methods by their complete resolved signature
 * - Discovering merged method annotations across type hierarchies
 *
 * @author Roland Beisel
 * @since 1.0.0
 */
internal object ReflectionUtils {
    /**
     * Resolves the actual class of the given bean.
     *
     * If the bean is an AOP proxy (e.g., for @Transactional), retrieves the target class
     * behind the proxy. Otherwise, returns the bean's own class.
     *
     * This is necessary because AOP proxies wrap the actual bean implementation,
     * and we need to access the real implementation class to find the correct methods.
     *
     * @param bean The object instance whose class is to be resolved
     * @return The resolved Java class of the bean or its target class
     */
    fun getTargetClass(bean: Any): Class<*> =
        if (AopUtils.isAopProxy(bean)) {
            AopUtils.getTargetClass(bean)
        } else {
            bean::class.java
        }

    /**
     * Resolves the payload type supplied to a generic handler interface.
     *
     * @param bean Bean implementing [handlerInterface]
     * @param handlerInterface Generic handler interface whose first type argument is the payload
     * @return Concrete payload type resolved through the bean's complete type hierarchy
     * @throws IllegalStateException if the payload type cannot be resolved
     */
    fun resolveInterfacePayloadType(
        bean: Any,
        handlerInterface: Class<*>,
    ): Class<*> =
        checkNotNull(
            ResolvableType
                .forClass(getTargetClass(bean))
                .`as`(handlerInterface)
                .getGeneric(0)
                .resolve(),
        ) {
            "Cannot resolve payload type for ${handlerInterface.name} on ${getTargetClass(bean).name}"
        }

    /**
     * Resolves the concrete method that implements a handler interface method.
     *
     * The declaration is selected by its exact erased interface signature. Spring then resolves
     * the most specific implementation and its bridged method, preventing unrelated overloads
     * with the same name and parameter count from being selected.
     *
     * @param bean The bean instance to search for the method
     * @param handlerInterface Handler interface declaring the method
     * @param methodName The name of the method to find
     * @param contextType Metadata or failure-context type expected as the second parameter
     * @return The most specific implementation method
     * @throws IllegalStateException if the bean does not implement the interface or the declared
     * interface method cannot be found
     */
    fun findInterfaceMethod(
        bean: Any,
        handlerInterface: Class<*>,
        methodName: String,
        contextType: Class<*>,
    ): Method {
        val targetClass = getTargetClass(bean)
        check(handlerInterface.isAssignableFrom(targetClass)) {
            "${targetClass.name} does not implement ${handlerInterface.name}"
        }

        val interfaceMethod =
            checkNotNull(
                ReflectionUtils.findMethod(
                    handlerInterface,
                    methodName,
                    Any::class.java,
                    contextType,
                ),
            ) {
                "Cannot find $methodName(${Any::class.java.name}, ${contextType.name}) on ${handlerInterface.name}"
            }

        val method = AopUtils.getMostSpecificMethod(interfaceMethod, targetClass)

        method.trySetAccessible()

        return method
    }

    /**
     * Finds all methods on the given bean that are annotated with the specified annotation.
     *
     * Filters out bridge and synthetic methods that are generated by the compiler.
     * Uses Spring's AnnotatedElementUtils to search for annotations in the method hierarchy
     * (class, interfaces, superclasses, meta-annotations).
     *
     * Example:
     * ```kotlin
     * val handlerMethods = ReflectionUtils.findAnnotatedMethods(bean, OutboxHandler::class.java)
     * ```
     *
     * @param bean The bean instance to search for annotated methods
     * @param annotationClass The annotation class to search for
     * @return Sequence of methods annotated with the specified annotation
     */
    fun <A : Annotation> findAnnotatedMethods(
        bean: Any,
        annotationClass: Class<A>,
    ): Sequence<Method> =
        MethodIntrospector
            .selectMethods(
                getTargetClass(bean),
                MethodIntrospector.MetadataLookup { method ->
                    AnnotatedElementUtils.findMergedAnnotation(method, annotationClass)
                },
            ).keys
            .asSequence()
            .onEach { it.trySetAccessible() }
}
